### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method launchUrl

### ISSUE THREAD

**Issue by dnikolaev** [marpies/AIRFacebook-ANE#4]
Hi @marpies,

There is a fatal exception with the latest version of [android-dependency-anes](https://github.com/marpies/android-dependency-anes)

```
FATAL EXCEPTION: main
Process: air.flirtymania.videochat, PID: 18467
java.lang.NoSuchMethodError: No virtual method launchUrl(Landroid/app/Activity;Landroid/net/Uri;)V in class Landroid/support/customtabs/CustomTabsIntent; or its super classes (declaration of 'android.support.customtabs.CustomTabsIntent' appears in /data/app/air.flirtymania.videochat-1/base.apk)
E/AndroidRuntime(18467): 	at com.facebook.internal.CustomTab.openCustomTab(CustomTab.java:48)
E/AndroidRuntime(18467): 	at com.facebook.CustomTabMainActivity.onCreate(CustomTabMainActivity.java:67)
E/AndroidRuntime(18467): 	at android.app.Activity.performCreate(Activity.java:6904)
E/AndroidRuntime(18467): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
E/AndroidRuntime(18467): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
E/AndroidRuntime(18467): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
E/AndroidRuntime(18467): 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
E/AndroidRuntime(18467): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
E/AndroidRuntime(18467): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18467): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(18467): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
E/AndroidRuntime(18467): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18467): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(18467): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
W/ActivityManager(2576):   Force finishing activity air.flirtymania.videochat/com.facebook.CustomTabMainActivity

```

**Comment by marpies** [comment]
Hi @dnikolaev,

Thanks for reporting.

Keep using v24 of Android support libraries for now. I'll need to update the Facebook SDK to be compatible with Android support v25.

**Comment by dnikolaev** [comment]
Thanks for info. I'm waiting for update.
